language: node_js
node_js:
- node
deploy:
  provider: npm
  email: anthony.kerz@gmail.com
  api_key:
    secure: 0blqUJaZ6g0maU23DqiNvIeIE2t+r2ejhzCUcA253ps/seInK3rtsyHnjZQSGPn1WzqX40DEwcy9nuuHQ43mqNWPMwCqt6G5uw8XdU2Ix4QaHZmoRVye2Oxwc1evodp7gQXCWIBdRhtkDAyqzVOsrEuTB7Ezg3tzsWFwjtYnUa9UU/22UdaU4dRuAkvYo+9uvhVMUAeu6P0aeoJirdsQQvAvfWdm42hJmTgm1L8aCqj/i/xdoEC/AFGFLlo+Cl4gSTPozNsj8vc5RI2elm6HfXqILR/wyisDUOPvctdKaWxe7Bxw4rPMDYh3QUM3RuE+J+AIhU7RW5fyZoc/06ZFHCivl0R6zanA/x2VVJm95VUn74mVUP44GkR1O8oPzc4qUEtBPxWjGyOP8ldWW/vAo+jL7L5ReUs8nAPD8rPOwRgra3+Q6pNqVmPMW0F9efLidVXP9TZFn3LdRria/hxtOTUT20ZcMZyy3xiul3a5DYcmZ5V7y15q+owVJPBNBuPlCxPPoDywdYwTSQb7SJboCPQ+4ptiCU6S2FNZ+nn6AOeiTg3PTSB6zoWnJl33XS9h08xAeohq0U9mnYxVsMdqdFNIG+JWl0Vv/sfpnuICahIzn7lRQnv3n2Kir9yo0rqtYQGZLQla7QcmAnqw4+9bajpaRvis1IIgTFCasoAu5uE=
  skip_cleanup: true
  on:
    branch: master
    condition: "-z $TRAVIS_TAG"
